# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  one:
    docker:
      -image: cimg/ruby:2.6.8
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD
  
  steps:
    -checkout
    -run: echo "A fisrt Hello word"
    -run: sleep 25
  two:
    docker:
      -image: cimg/ruby:3.0.2
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD
  
  steps:
    -checkout
    -run: echo "A second Hello word"
    -run: sleep 15


workflows:
  version: 2.1
  one_and_two:
    jobs:
      -one
      -two



