version: 2.1

jobs:
  one:
    docker:
      - image: cimg/ruby:2.6.8
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A first Hello word"
      - run: sleep 25

  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo "A second Hello word"
      - run: sleep 15

workflows:
  version: 2.1
  one_and_two:
    jobs:
      - one
      - two
